db:
  src:
    dsn: "root:root@tcp(localhost:13316)/webookpro"
  dst:
    dsn: "root:root@tcp(localhost:13316)/webookpro-intr"

migrator:
  pattern: "SRC_ONLY"
  web:
    addr: ":8082"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"
    -
grpc:
  client:
    intr:
      addr: "localhost:8090"
      secure: false
      threshold: 100